[default.extend-words]
Nd = "Nd"
[files]
extend-exclude = [
    "CHANGELOG.md",
    "chat/chat_server/fixtures/*",
    "chat/chat_core/fixtures/*",
    "chat/notify_server/*.html",
    "chatapp/src/gen/*",
]
